# Generated by Django 3.2.8 on 2021-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadoku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='yl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readbooks',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
